spring.application.name=base-postpizza
spring.datasource.url=jdbc:postgresql://ep-tiny-frog-aqm8967q-pooler.c-8.us-east-1.aws.neon.tech/neondb
spring.datasource.username=neondb_owner
spring.datasource.password=npg_2cHzxCAQF7YU